analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6729323
  brandStrength: 1
  lightness: 0.5955961
  brandColors:
    - '#000000'
    - '#FF3D24'
    - '#FFFFFF'
    - '#00448E'
    - '#767676'
  rhythmicContrast: 0.858754
typography_spectrum: 0.6847476
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8549687252379954
favicon: null
name: DreAllDay
