name: DreAllDay
favicon: null
layout_spectrum: 0.8549687252379954
typography_spectrum: 0.8974178470671177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7056215305346996
  lightness: 0.9016302097588778
  saturation: 0.6193660795688629
  rhythmicContrast: 0.7115715018007904
purpose: []
